name: Build & Deploy Portfolio to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 1) Client build
      - name: Install & build React client
        working-directory: client
        run: |
          npm ci
          npm run build

      # 2) Server deps
      - name: Install server dependencies
        working-directory: server
        run: npm ci

      # 3) Prepare artifact
      - name: Assemble dist folder
        run: |
          rm -rf dist
          mkdir -p dist
          # Copy server code
          cp -r server dist/server
          # Copy package files into server folder
          cp server/package*.json dist/server/
          # Move client build into server for static serving
          mkdir -p dist/server/client
          cp -r client/build/* dist/server/client

      # 4) Zip it up
      - name: Zip release artifact
        working-directory: dist/server
        run: zip -r ../../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}    # e.g. “Portfolio”
          slot-name: Production
          package: .                                   # unzipped dist/server here
