name: Build & Deploy Portfolio to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install & build
        run: |
          npm ci
          npm run build
          npm run test --if-present

      - name: Prepare artifact folder
        run: |
          rm -rf dist
          mkdir -p dist
          # Copy server.js and package.json
          cp server.js package*.json dist/
          # Copy node_modules
          cp -r node_modules dist/node_modules
          # Copy React build output to correct location
          cp -r build dist/build

      - name: Zip artifact
        run: |
          cd dist
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: .
